//
// Created by Brunshweeck on 12/09/2023.
//

#include <core/util/HashMap.h>
#include <core/util/TreeMap.h>
#include <core/Character.h>
#include <core/String.h>
#include "Enum.h"

using core::util::HashMap;
using core::util::TreeMap;

namespace core {

    namespace {
        HashMap <String, Object> *SharedSecrets = {};
    }

    namespace {
        interface EnumCAT : public Enum<Character::Category> {
            EnumCAT(const String &name, gint ordinal) : Enum<Character::Category>(name, ordinal) {}
        };

        interface EnumCCC : public Enum<Character::CombiningClass> {
            EnumCCC(const String &name, gint ordinal) : Enum<Character::CombiningClass>(name, ordinal) {}
        };

        interface EnumDIR : public Enum<Character::Directionality> {
            EnumDIR(const String &name, gint ordinal) : Enum<Character::Directionality>(name, ordinal) {}
        };

        interface EnumDEC : public Enum<Character::Decomposition> {
            EnumDEC(const String &name, gint ordinal) : Enum<Character::Decomposition>(name, ordinal) {}
        };

        interface EnumUNB : public Enum<Character::UnicodeBlock> {
            EnumUNB(const String &name, gint ordinal) : Enum<Character::UnicodeBlock>(name, ordinal) {}
        };

        interface EnumUNS : public Enum<Character::UnicodeScript> {
            EnumUNS(const String &name, gint ordinal) : Enum<Character::UnicodeScript>(name, ordinal) {}
        };


    }

    namespace native {
        Object &Unsafe::systemCache() {
            if (SharedSecrets == 0) {
                SharedSecrets = &createInstance<HashMap<String, Object>>(500, 0.75);
            } else {
                // characters enums
                {
                    CORE_FAST const char *str[30] = {
                            "NON_SPACING_MARK",
                            "COMBINING_SPACING_MARK",
                            "ENCLOSING_MARK",
                            "DECIMAL_DIGIT_NUMBER",
                            "LETTER_NUMBER",
                            "OTHER_NUMBER",
                            "SPACE_SEPARATOR",
                            "LINE_SEPARATOR",
                            "PARAGRAPH_SEPARATOR",
                            "CONTROL",
                            "FORMAT",
                            "SURROGATE",
                            "PRIVATE_USE",
                            "UNASSIGNED",
                            "UPPERCASE_LETTER",
                            "LOWERCASE_LETTER",
                            "TITLECASE_LETTER",
                            "MODIFIER_LETTER",
                            "OTHER_LETTER",
                            "CONNECTOR_PUNCTUATION",
                            "DASH_PUNCTUATION",
                            "START_PUNCTUATION",
                            "END_PUNCTUATION",
                            "INITIAL_QUOTE_PUNCTUATION",
                            "FINAL_QUOTE_PUNCTUATION",
                            "OTHER_PUNCTUATION",
                            "MATH_SYMBOL",
                            "CURRENCY_SYMBOL",
                            "MODIFIER_SYMBOL",
                            "OTHER_SYMBOL",
                    };
                    for (int i = 0; i < 30; ++i) {
                        EnumCAT(String(str[i] + 0), i);
                    }
                };
                {
                    CORE_FAST const char *str[24] = {
                            "UNASSIGNED",
                            "LEFT_TO_RIGHT",
                            "RIGHT_TO_LEFT",
                            "RIGHT_TO_LEFT_ARABIC",
                            "EUROPEAN_NUMBER",
                            "EUROPEAN_NUMBER_SEPARATOR",
                            "EUROPEAN_NUMBER_TERMINATOR",
                            "ARABIC_NUMBER",
                            "COMMON_NUMBER_SEPARATOR",
                            "NON_SPACING_MARK",
                            "BOUNDARY_NEUTRAL",
                            "PARAGRAPH_SEPARATOR",
                            "SEGMENT_SEPARATOR",
                            "WHITESPACE",
                            "OTHER_NEUTRALS",
                            "LEFT_TO_RIGHT_EMBEDDING",
                            "LEFT_TO_RIGHT_OVERRIDE",
                            "RIGHT_TO_LEFT_EMBEDDING",
                            "RIGHT_TO_LEFT_OVERRIDE",
                            "POP_DIRECTIONAL_FORMAT",
                            "LEFT_TO_RIGHT_ISOLATE",
                            "RIGHT_TO_LEFT_ISOLATE",
                            "FIRST_STRONG_ISOLATE",
                            "POP_DIRECTIONAL_ISOLATE",
                    };
                    for (int i = 0; i < 24; ++i) {
                        EnumDIR(String(str[i] + 0), i);
                    }
                };
                {
                    CORE_FAST const char *str[164] = {
                            "COMMON",
                            "LATIN",
                            "GREEK",
                            "CYRILLIC",
                            "ARMENIAN",
                            "HEBREW",
                            "ARABIC",
                            "SYRIAC",
                            "THAANA",
                            "DEVANAGARI",
                            "BENGALI",
                            "GURMUKHI",
                            "GUJARATI",
                            "ORIYA",
                            "TAMIL",
                            "TELUGU",
                            "KANNADA",
                            "MALAYALAM",
                            "SINHALA",
                            "THAI",
                            "LAO",
                            "TIBETAN",
                            "MYANMAR",
                            "GEORGIAN",
                            "HANGUL",
                            "ETHIOPIC",
                            "CHEROKEE",
                            "CANADIAN_ABORIGINAL",
                            "OGHAM",
                            "RUNIC",
                            "KHMER",
                            "MONGOLIAN",
                            "HIRAGANA",
                            "KATAKANA",
                            "BOPOMOFO",
                            "HAN",
                            "YI",
                            "OLD_ITALIC",
                            "GOTHIC",
                            "DESERET",
                            "INHERITED",
                            "TAGALOG",
                            "HANUNOO",
                            "BUHID",
                            "TAGBANWA",
                            "LIMBU",
                            "TAI_LE",
                            "LINEAR_B",
                            "UGARITIC",
                            "SHAVIAN",
                            "OSMANYA",
                            "CYPRIOT",
                            "BRAILLE",
                            "BUGINESE",
                            "COPTIC",
                            "NEW_TAI_LUE",
                            "GLAGOLITIC",
                            "TIFINAGH",
                            "SYLOTI_NAGRI",
                            "OLD_PERSIAN",
                            "KHAROSHTHI",
                            "BALINESE",
                            "CUNEIFORM",
                            "PHOENICIAN",
                            "PHAGS_PA",
                            "NKO",
                            "SUNDANESE",
                            "BATAK",
                            "LEPCHA",
                            "OL_CHIKI",
                            "VAI",
                            "SAURASHTRA",
                            "KAYAH_LI",
                            "REJANG",
                            "LYCIAN",
                            "CARIAN",
                            "LYDIAN",
                            "CHAM",
                            "TAI_THAM",
                            "TAI_VIET",
                            "AVESTAN",
                            "EGYPTIAN_HIEROGLYPHS",
                            "SAMARITAN",
                            "MANDAIC",
                            "LISU",
                            "BAMUM",
                            "JAVANESE",
                            "MEETEI_MAYEK",
                            "IMPERIAL_ARAMAIC",
                            "OLD_SOUTH_ARABIAN",
                            "INSCRIPTIONAL_PARTHIAN",
                            "INSCRIPTIONAL_PAHLAVI",
                            "OLD_TURKIC",
                            "BRAHMI",
                            "KAITHI",
                            "MEROITIC_HIEROGLYPHS",
                            "MEROITIC_CURSIVE",
                            "SORA_SOMPENG",
                            "CHAKMA",
                            "SHARADA",
                            "TAKRI",
                            "MIAO",
                            "CAUCASIAN_ALBANIAN",
                            "BASSA_VAH",
                            "DUPLOYAN",
                            "ELBASAN",
                            "GRANTHA",
                            "PAHAWH_HMONG",
                            "KHOJKI",
                            "LINEAR_A",
                            "MAHAJANI",
                            "MANICHAEAN",
                            "MENDE_KIKAKUI",
                            "MODI",
                            "MRO",
                            "OLD_NORTH_ARABIAN",
                            "NABATAEAN",
                            "PALMYRENE",
                            "PAU_CIN_HAU",
                            "OLD_PERMIC",
                            "PSALTER_PAHLAVI",
                            "SIDDHAM",
                            "KHUDAWADI",
                            "TIRHUTA",
                            "WARANG_CITI",
                            "AHOM",
                            "ANATOLIAN_HIEROGLYPHS",
                            "HATRAN",
                            "MULTANI",
                            "OLD_HUNGARIAN",
                            "SIGNWRITING",
                            "ADLAM",
                            "BHAIKSUKI",
                            "MARCHEN",
                            "NEWA",
                            "OSAGE",
                            "TANGUT",
                            "MASARAM_GONDI",
                            "NUSHU",
                            "SOYOMBO",
                            "ZANABAZAR_SQUARE",
                            "HANIFI_ROHINGYA",
                            "OLD_SOGDIAN",
                            "SOGDIAN",
                            "DOGRA",
                            "GUNJALA_GONDI",
                            "MAKASAR",
                            "MEDEFAIDRIN",
                            "ELYMAIC",
                            "NANDINAGARI",
                            "NYIAKENG_PUACHUE_HMONG",
                            "WANCHO",
                            "YEZIDI",
                            "CHORASMIAN",
                            "DIVES_AKURU",
                            "KHITAN_SMALL_SCRIPT",
                            "VITHKUQI",
                            "OLD_UYGHUR",
                            "CYPRO_MINOAN",
                            "TANGSA",
                            "TOTO",
                            "KAWI",
                            "NAG_MUNDARI",
                            "UNKNOWN",
                    };
                    for (int i = 0; i < 164; ++i) {
                        EnumUNS(String(str[i] + 0), i);
                    }
                };
                {
                    CORE_FAST const char *str[329] = {
                            "BASIC_LATIN",
                            "LATIN_1_SUPPLEMENT",
                            "LATIN_EXTENDED_A",
                            "LATIN_EXTENDED_B",
                            "IPA_EXTENSIONS",
                            "SPACING_MODIFIER_LETTERS",
                            "COMBINING_DIACRITICAL_MARKS",
                            "GREEK",
                            "CYRILLIC",
                            "ARMENIAN",
                            "HEBREW",
                            "ARABIC",
                            "DEVANAGARI",
                            "BENGALI",
                            "GURMUKHI",
                            "GUJARATI",
                            "ORIYA",
                            "TAMIL",
                            "TELUGU",
                            "KANNADA",
                            "MALAYALAM",
                            "THAI",
                            "LAO",
                            "TIBETAN",
                            "GEORGIAN",
                            "HANGUL_JAMO",
                            "LATIN_EXTENDED_ADDITIONAL",
                            "GREEK_EXTENDED",
                            "GENERAL_PUNCTUATION",
                            "SUPERSCRIPTS_AND_SUBSCRIPTS",
                            "CURRENCY_SYMBOLS",
                            "COMBINING_MARKS_FOR_SYMBOLS",
                            "LETTERLIKE_SYMBOLS",
                            "NUMBER_FORMS",
                            "ARROWS",
                            "MATHEMATICAL_OPERATORS",
                            "MISCELLANEOUS_TECHNICAL",
                            "CONTROL_PICTURES",
                            "OPTICAL_CHARACTER_RECOGNITION",
                            "ENCLOSED_ALPHANUMERICS",
                            "BOX_DRAWING",
                            "BLOCK_ELEMENTS",
                            "GEOMETRIC_SHAPES",
                            "MISCELLANEOUS_SYMBOLS",
                            "DINGBATS",
                            "CJK_SYMBOLS_AND_PUNCTUATION",
                            "HIRAGANA",
                            "KATAKANA",
                            "BOPOMOFO",
                            "HANGUL_COMPATIBILITY_JAMO",
                            "KANBUN",
                            "ENCLOSED_CJK_LETTERS_AND_MONTHS",
                            "CJK_COMPATIBILITY",
                            "CJK_UNIFIED_IDEOGRAPHS",
                            "HANGUL_SYLLABLES",
                            "PRIVATE_USE_AREA",
                            "CJK_COMPATIBILITY_IDEOGRAPHS",
                            "ALPHABETIC_PRESENTATION_FORMS",
                            "ARABIC_PRESENTATION_FORMS_A",
                            "COMBINING_HALF_MARKS",
                            "CJK_COMPATIBILITY_FORMS",
                            "SMALL_FORM_VARIANTS",
                            "ARABIC_PRESENTATION_FORMS_B",
                            "HALFWIDTH_AND_FULLWIDTH_FORMS",
                            "SPECIALS",
                            "SURROGATES_AREA",
                            "SYRIAC",
                            "THAANA",
                            "SINHALA",
                            "MYANMAR",
                            "ETHIOPIC",
                            "CHEROKEE",
                            "UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS",
                            "OGHAM",
                            "RUNIC",
                            "KHMER",
                            "MONGOLIAN",
                            "BRAILLE_PATTERNS",
                            "CJK_RADICALS_SUPPLEMENT",
                            "KANGXI_RADICALS",
                            "IDEOGRAPHIC_DESCRIPTION_CHARACTERS",
                            "BOPOMOFO_EXTENDED",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A",
                            "YI_SYLLABLES",
                            "YI_RADICALS",
                            "CYRILLIC_SUPPLEMENTARY",
                            "TAGALOG",
                            "HANUNOO",
                            "BUHID",
                            "TAGBANWA",
                            "LIMBU",
                            "TAI_LE",
                            "KHMER_SYMBOLS",
                            "PHONETIC_EXTENSIONS",
                            "MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A",
                            "SUPPLEMENTAL_ARROWS_A",
                            "SUPPLEMENTAL_ARROWS_B",
                            "MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B",
                            "SUPPLEMENTAL_MATHEMATICAL_OPERATORS",
                            "MISCELLANEOUS_SYMBOLS_AND_ARROWS",
                            "KATAKANA_PHONETIC_EXTENSIONS",
                            "YIJING_HEXAGRAM_SYMBOLS",
                            "VARIATION_SELECTORS",
                            "LINEAR_B_SYLLABARY",
                            "LINEAR_B_IDEOGRAMS",
                            "AEGEAN_NUMBERS",
                            "OLD_ITALIC",
                            "GOTHIC",
                            "UGARITIC",
                            "DESERET",
                            "SHAVIAN",
                            "OSMANYA",
                            "CYPRIOT_SYLLABARY",
                            "BYZANTINE_MUSICAL_SYMBOLS",
                            "MUSICAL_SYMBOLS",
                            "TAI_XUAN_JING_SYMBOLS",
                            "MATHEMATICAL_ALPHANUMERIC_SYMBOLS",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B",
                            "CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT",
                            "TAGS",
                            "VARIATION_SELECTORS_SUPPLEMENT",
                            "SUPPLEMENTARY_PRIVATE_USE_AREA_A",
                            "SUPPLEMENTARY_PRIVATE_USE_AREA_B",
                            "HIGH_SURROGATES",
                            "HIGH_PRIVATE_USE_SURROGATES",
                            "LOW_SURROGATES",
                            "ARABIC_SUPPLEMENT",
                            "NKO",
                            "SAMARITAN",
                            "MANDAIC",
                            "ETHIOPIC_SUPPLEMENT",
                            "UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED",
                            "NEW_TAI_LUE",
                            "BUGINESE",
                            "TAI_THAM",
                            "BALINESE",
                            "SUNDANESE",
                            "BATAK",
                            "LEPCHA",
                            "OL_CHIKI",
                            "VEDIC_EXTENSIONS",
                            "PHONETIC_EXTENSIONS_SUPPLEMENT",
                            "COMBINING_DIACRITICAL_MARKS_SUPPLEMENT",
                            "GLAGOLITIC",
                            "LATIN_EXTENDED_C",
                            "COPTIC",
                            "GEORGIAN_SUPPLEMENT",
                            "TIFINAGH",
                            "ETHIOPIC_EXTENDED",
                            "CYRILLIC_EXTENDED_A",
                            "SUPPLEMENTAL_PUNCTUATION",
                            "CJK_STROKES",
                            "LISU",
                            "VAI",
                            "CYRILLIC_EXTENDED_B",
                            "BAMUM",
                            "MODIFIER_TONE_LETTERS",
                            "LATIN_EXTENDED_D",
                            "SYLOTI_NAGRI",
                            "COMMON_INDIC_NUMBER_FORMS",
                            "PHAGS_PA",
                            "SAURASHTRA",
                            "DEVANAGARI_EXTENDED",
                            "KAYAH_LI",
                            "REJANG",
                            "HANGUL_JAMO_EXTENDED_A",
                            "JAVANESE",
                            "CHAM",
                            "MYANMAR_EXTENDED_A",
                            "TAI_VIET",
                            "ETHIOPIC_EXTENDED_A",
                            "MEETEI_MAYEK",
                            "HANGUL_JAMO_EXTENDED_B",
                            "VERTICAL_FORMS",
                            "ANCIENT_GREEK_NUMBERS",
                            "ANCIENT_SYMBOLS",
                            "PHAISTOS_DISC",
                            "LYCIAN",
                            "CARIAN",
                            "OLD_PERSIAN",
                            "IMPERIAL_ARAMAIC",
                            "PHOENICIAN",
                            "LYDIAN",
                            "KHAROSHTHI",
                            "OLD_SOUTH_ARABIAN",
                            "AVESTAN",
                            "INSCRIPTIONAL_PARTHIAN",
                            "INSCRIPTIONAL_PAHLAVI",
                            "OLD_TURKIC",
                            "RUMI_NUMERAL_SYMBOLS",
                            "BRAHMI",
                            "KAITHI",
                            "CUNEIFORM",
                            "CUNEIFORM_NUMBERS_AND_PUNCTUATION",
                            "EGYPTIAN_HIEROGLYPHS",
                            "BAMUM_SUPPLEMENT",
                            "KANA_SUPPLEMENT",
                            "ANCIENT_GREEK_MUSICAL_NOTATION",
                            "COUNTING_ROD_NUMERALS",
                            "MAHJONG_TILES",
                            "DOMINO_TILES",
                            "PLAYING_CARDS",
                            "ENCLOSED_ALPHANUMERIC_SUPPLEMENT",
                            "ENCLOSED_IDEOGRAPHIC_SUPPLEMENT",
                            "MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS",
                            "EMOTICONS",
                            "TRANSPORT_AND_MAP_SYMBOLS",
                            "ALCHEMICAL_SYMBOLS",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D",
                            "ARABIC_EXTENDED_A",
                            "SUNDANESE_SUPPLEMENT",
                            "MEETEI_MAYEK_EXTENSIONS",
                            "MEROITIC_HIEROGLYPHS",
                            "MEROITIC_CURSIVE",
                            "SORA_SOMPENG",
                            "CHAKMA",
                            "SHARADA",
                            "TAKRI",
                            "MIAO",
                            "ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS",
                            "COMBINING_DIACRITICAL_MARKS_EXTENDED",
                            "MYANMAR_EXTENDED_B",
                            "LATIN_EXTENDED_E",
                            "COPTIC_EPACT_NUMBERS",
                            "OLD_PERMIC",
                            "ELBASAN",
                            "CAUCASIAN_ALBANIAN",
                            "LINEAR_A",
                            "PALMYRENE",
                            "NABATAEAN",
                            "OLD_NORTH_ARABIAN",
                            "MANICHAEAN",
                            "PSALTER_PAHLAVI",
                            "MAHAJANI",
                            "SINHALA_ARCHAIC_NUMBERS",
                            "KHOJKI",
                            "KHUDAWADI",
                            "GRANTHA",
                            "TIRHUTA",
                            "SIDDHAM",
                            "MODI",
                            "WARANG_CITI",
                            "PAU_CIN_HAU",
                            "MRO",
                            "BASSA_VAH",
                            "PAHAWH_HMONG",
                            "DUPLOYAN",
                            "SHORTHAND_FORMAT_CONTROLS",
                            "MENDE_KIKAKUI",
                            "ORNAMENTAL_DINGBATS",
                            "GEOMETRIC_SHAPES_EXTENDED",
                            "SUPPLEMENTAL_ARROWS_C",
                            "CHEROKEE_SUPPLEMENT",
                            "HATRAN",
                            "OLD_HUNGARIAN",
                            "MULTANI",
                            "AHOM",
                            "EARLY_DYNASTIC_CUNEIFORM",
                            "ANATOLIAN_HIEROGLYPHS",
                            "SUTTON_SIGNWRITING",
                            "SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E",
                            "SYRIAC_SUPPLEMENT",
                            "CYRILLIC_EXTENDED_C",
                            "OSAGE",
                            "NEWA",
                            "MONGOLIAN_SUPPLEMENT",
                            "MARCHEN",
                            "IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION",
                            "TANGUT",
                            "TANGUT_COMPONENTS",
                            "KANA_EXTENDED_A",
                            "GLAGOLITIC_SUPPLEMENT",
                            "ADLAM",
                            "MASARAM_GONDI",
                            "ZANABAZAR_SQUARE",
                            "NUSHU",
                            "SOYOMBO",
                            "BHAIKSUKI",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F",
                            "GEORGIAN_EXTENDED",
                            "HANIFI_ROHINGYA",
                            "OLD_SOGDIAN",
                            "SOGDIAN",
                            "DOGRA",
                            "GUNJALA_GONDI",
                            "MAKASAR",
                            "MEDEFAIDRIN",
                            "MAYAN_NUMERALS",
                            "INDIC_SIYAQ_NUMBERS",
                            "CHESS_SYMBOLS",
                            "ELYMAIC",
                            "NANDINAGARI",
                            "TAMIL_SUPPLEMENT",
                            "EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS",
                            "SMALL_KANA_EXTENSION",
                            "NYIAKENG_PUACHUE_HMONG",
                            "WANCHO",
                            "OTTOMAN_SIYAQ_NUMBERS",
                            "SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A",
                            "YEZIDI",
                            "CHORASMIAN",
                            "DIVES_AKURU",
                            "LISU_SUPPLEMENT",
                            "KHITAN_SMALL_SCRIPT",
                            "TANGUT_SUPPLEMENT",
                            "SYMBOLS_FOR_LEGACY_COMPUTING",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G",
                            "ARABIC_EXTENDED_B",
                            "VITHKUQI",
                            "LATIN_EXTENDED_F",
                            "OLD_UYGHUR",
                            "UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A",
                            "CYPRO_MINOAN",
                            "TANGSA",
                            "KANA_EXTENDED_B",
                            "ZNAMENNY_MUSICAL_NOTATION",
                            "LATIN_EXTENDED_G",
                            "TOTO",
                            "ETHIOPIC_EXTENDED_B",
                            "ARABIC_EXTENDED_C",
                            "DEVANAGARI_EXTENDED_A",
                            "KAWI",
                            "KAKTOVIK_NUMERALS",
                            "CYRILLIC_EXTENDED_D",
                            "NAG_MUNDARI",
                            "CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H",
                            "UNASSIGNED",
                    };
                    for (int i = 0; i < 329; ++i) {
                        EnumUNB(String(str[i] + 0), i);
                    }
                };
                {
                    CORE_FAST const char *str[18] = {
                            "UNDEFINED",
                            "CANONICAL",
                            "FONT",
                            "NO_BREAK",
                            "INITIAL",
                            "MEDIAL",
                            "FINAL",
                            "ISOLATED",
                            "CIRCLE",
                            "SUPER",
                            "SUB",
                            "VERTICAL",
                            "WIDE",
                            "NARROW",
                            "SMALL",
                            "SQUARE",
                            "COMPAT",
                            "FRACTION",
                    };
                    for (int i = 0; i < 18; ++i) {
                        EnumDEC(String(str[i] + 0), i);
                    }
                };
                {
                    EnumCCC("UNDEFINED", 0);
                    EnumCCC("BELOW_LEFT_ATTACHED", 200);
                    EnumCCC("BELOW_ATTACHED", 202);
                    EnumCCC("BELOW_RIGHT_ATTACHED", 204);
                    EnumCCC("LEFT_ATTACHED", 208);
                    EnumCCC("RIGHT_ATTACHED", 210);
                    EnumCCC("ABOVE_LEFT_ATTACHED", 212);
                    EnumCCC("ABOVE_ATTACHED", 214);
                    EnumCCC("ABOVE_RIGHT_ATTACHED", 216);
                    EnumCCC("BELOW_LEFT", 218);
                    EnumCCC("BELOW", 220);
                    EnumCCC("BELOW_RIGHT", 222);
                    EnumCCC("LEFT", 224);
                    EnumCCC("RIGHT", 226);
                    EnumCCC("ABOVE_LEFT", 228);
                    EnumCCC("ABOVE", 230);
                    EnumCCC("ABOVE_RIGHT", 232);
                    EnumCCC("DOUBLE_BELOW", 233);
                    EnumCCC("DOUBLE_ABOVE", 234);
                    EnumCCC("IOTA_SUBSCRIPT", 240);
                };
                // locales enums
            }
            return SharedSecrets[0];
        }
    }

} // core